# Generated by Django 2.2 on 2019-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20190424_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plain_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/plain_images'),
        ),
    ]
