# Generated by Django 2.2 on 2019-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_plain_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plain_image',
        ),
    ]
