# Generated by Django 2.2 on 2019-04-24 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20190424_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instauser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
    ]
