# Generated by Django 2.2 on 2019-04-24 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20190424_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='instauser',
            name='following',
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('instaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
