# Generated by Django 2.2.1 on 2019-05-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0013_instapost_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapost',
            name='image',
        ),
    ]
