# Generated by Django 2.2.1 on 2019-05-03 23:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0014_remove_instapost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapost',
            name='upload',
        ),
        migrations.AddField(
            model_name='instapost',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
